fullnameOverride: kps
prometheus:
  prometheusSpec:
    insecureSkipVerify: true
    scrapeInterval: 1m
    retention: 2h
    retentionSize: 500MB
    resources:
      requests:
        cpu: 100m
        memory: 250Mi
      limits:
        cpu: 400m
        memory: 500Mi
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
    additionalAlertManagers:
      - namespace: monitoring
        name: alertmanager-kps-alertmanager
        port: web
