apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blackbox-exporter
  namespace: argo
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: prometheus-blackbox-exporter
      targetRevision: 9.3.0 # Актуальная стабильная версия чарта
      helm:
        valueFiles:
          - $values/module-10/values/monitoring/blackbox-values.yaml
    - repoURL: https://github.com/engorohov/labs
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

