apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argo
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: loki
      targetRevision: 6.6.0
      helm:
        valueFiles:
          - $values/module-10/values/monitoring/loki-values.yaml
    - repoURL: https://github.com/engorohov/labs
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

