{
 "title": "four",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Количество реплик",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{namespace=\"podinfo-dev\", deployment=\"demo\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{namespace=\"podinfo-dev\"}[5m]))",
     "legendFormat": "{{rps}}"
    }
   ]
  },
  {
   "title": "p95 latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(http_request_duration_seconds_bucket{namespace=\"podinfo-dev\"}[5m])))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Error rate (5xx %)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((sum(rate(http_requests_total{namespace=\"podinfo-dev\", status=~\"5..\"}[5m])) / sum(rate(http_requests_total{namespace=\"podinfo-dev\"}[5m]))) * 100) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}