tempo:
  auth_enabled: false
  storage:
    trace:
      backend: local
      local:
        path: /var/tempo/traces
      wal:
        path: /var/tempo/wal

# Запускаем в режиме одного пода
singleBinary:
  replicas: 1
  persistence:
    enabled: true
    size: 1Gi

# ВКЛЮЧАЕМ ПРИЕМ ТРЕЙСОВ ОТ ПОДОВ (Этот блок откроет порт 4317!)
distributor:
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

# Отключаем лишние компоненты, чтобы сэкономить ресурсы сервера
ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
compactor:
  replicas: 0
metricsGenerator:
  enabled: false

