fullnameOverride: kps
prometheus:
  prometheusSpec:
    insecureSkipVerify: true
    scrapeInterval: 1m
    retention: 2h
    retentionSize: 500MB
    resources:
      requests:
        cpu: 20m
        memory: 250Mi
      limits:
        memory: 250Mi
    # включить автоматическое подхватывание ServiceMonitor из всех неймспейсов
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

fullnameOverride: kps
alertmanager:
  # Изменяем конфигурацию самого Хельм-чарта:
  alertmanagerSpec:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname', 'severity']
      group_wait: 10s
      group_interval: 30s
      repeat_interval: 1h
      receiver: 'telegram'
      routes:
        - matchers:
            - alertname="Watchdog"
          receiver: 'null'
        - matchers:
            - severity="critical"
          receiver: 'telegram-critical'
          group_wait: 5s
          repeat_interval: 30m
    receivers:
      - name: 'telegram'
        telegram_configs:
          # Ссылаемся на переменные, которые Кубер развернет из секретных файлов!
          - bot_token: "{{ .Values.alertmanager.secretConfig.bot_token }}"
            chat_id: "{{ .Values.alertmanager.secretConfig.chat_id }}"
            parse_mode: 'HTML'
            send_resolved: true
            message: |
              {{ range .Alerts }}
              <b>{{ .Labels.alertname }}</b> [{{ .Labels.severity }}]
              {{ .Annotations.summary }}
              {{ .Annotations.description }}
              {{ end }}
      - name: 'telegram-critical'
        telegram_configs:
          - bot_token: "{{ .Values.alertmanager.secretConfig.bot_token }}"
            chat_id: "{{ .Values.alertmanager.secretConfig.chat_id }}"
            parse_mode: 'HTML'
            send_resolved: true
            message: |
              🔥🔥🔥 CRITICAL 🔥🔥🔥
              {{ range .Alerts }}
              <b>{{ .Labels.alertname }}</b>
              {{ .Annotations.summary }}
              {{ .Annotations.description }}
              {{ end }}

  # А вот сюда, в самый низ блока alertmanager (на уровне config), мы безопасно подмешиваем Хельму 
  # указание взять данные из нашего секретного объекта, который мы создали руками на сервере!
  secretConfig:
    bot_token: "alertmanager-telegram-secret:bot_token"
    chat_id: "alertmanager-telegram-secret:chat_id"

grafana:
  # Безопасный импорт логина и пароля из секрета K8s
  admin:
    existingSecret: "grafana-admin-secret"
    userKey: "admin-user"
    passwordKey: "admin-password"
  service:
    type: ClusterIP
  persistence:
    enabled: true
    size: 5Gi
  defaultDashboardsTimezone: browser
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default

#node-exporter поставится автоматически как DaemonSet на каждом узле
nodeExporter:
  enabled: true
#kube-state-metrics поставится автоматически
kube-state-metrics:
  enabled: true
